MIN_COOKING_TIME = 1
MIN_INGREDIENT_AMOUNT = 1
RECIPE_NOT_FOUND = 'Рецепт {} не найден.'
RECIPE_NOT_IN_FAVORITE = 'Рецепт {} не добавлен в избранное.'
RECIPE_IN_FAVORITE = 'Рецепт {} уже есть в избранном.'
RECIPE_NOT_IN_SHOPPING = 'Рецепт {} не добавлен в список покупок.'
RECIPE_IN_SHOPPING = 'Рецепт {} уже есть в списке покупок.'
SUBSCRIPTION_NOT_FOUND = 'Вы не подписаны на пользователя {}'
ADD_TAGS = 'Добавьте теги.'
ADD_INGREDIENTS = 'Добавьте ингредиенты.'
DUPLICATE_TAGS = 'Теги рецепта не должны повторяться.'
DUPLICATE_INGREDIENTS = 'Ингредиенты рецепта не должны повторяться.'
SUBSCRIBE_SELF = 'Нельзя подписаться на самого себя.'
EXIST_IN_SUBSCRIBING = 'Вы уже подписаны на пользователя {}'
