MIN_COOKING_TIME = 1
MIN_INGREDIENT_AMOUNT = 1
MAX_USERNAME = 150
MAX_EMAIL = 254
MAX_FIRST_NAME = 150
MAX_LAST_NAME = 150
MAX_TAG_NAME = 200
MAX_TAG_COLOR = 7
MAX_TAG_SLUG = 200
MAX_RECIPE_NAME = 200
MAX_INGREDIENT_NAME = 200
MAX_INGREDIENT_MEASURE = 200
USERNAME_REGEX = r'^[\w.@+-]+\Z'
RECIPE_NOT_FOUND = 'Рецепт {} не найден.'
RECIPE_NOT_IN_FAVORITE = 'Рецепт {} не добавлен в избранное.'
RECIPE_IN_FAVORITE = 'Рецепт {} уже есть в избранном.'
RECIPE_NOT_IN_SHOPPING = 'Рецепт {} не добавлен в список покупок.'
RECIPE_IN_SHOPPING = 'Рецепт {} уже есть в списке покупок.'
SUBSCRIPTION_NOT_FOUND = 'Вы не подписаны на пользователя {}'
ADD_TAGS = 'Добавьте теги.'
ADD_INGREDIENTS = 'Добавьте ингредиенты.'
DUPLICATE_TAGS = 'Теги рецепта не должны повторяться.'
DUPLICATE_INGREDIENTS = 'Ингредиенты рецепта не должны повторяться.'
SUBSCRIBE_SELF = 'Нельзя подписаться на самого себя.'
EXIST_IN_SUBSCRIBING = 'Вы уже подписаны на пользователя {}'
