# Generated by Django 3.2.16 on 2024-02-29 08:11

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, unique=True, validators=[recipes.validators.ColorValidator()], verbose_name='Код цвета'),
        ),
    ]
