# Generated by Django 3.2.16 on 2024-02-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240213_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingridients',
            options={'verbose_name': 'Ингредиент рецепта', 'verbose_name_plural': 'ингредиенты рецепта'},
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
    ]
