# Generated by Django 3.2.16 on 2024-02-14 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'default_related_name': 'users', 'ordering': ['username'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'пользователи'},
        ),
    ]
