# Generated by Django 3.2.16 on 2024-02-14 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20240214_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredients',
            old_name='ingridient',
            new_name='ingredient',
        ),
    ]
