# Generated by Django 3.2.16 on 2024-02-15 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20240215_0915'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngredients',
            new_name='Meal',
        ),
    ]
