# Generated by Django 3.2.16 on 2024-02-15 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_rename_recipeingredients_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='ingredient',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingredient_to_recipe', to='recipes.ingredient', verbose_name='Ингредиент'),
        ),
    ]
