# Generated by Django 3.2.16 on 2024-02-16 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20240215_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
