# Generated by Django 3.2.16 on 2024-02-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_alter_meal_amount'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_recipe_ingredient'),
        ),
    ]
